
name: Build and publish to gh pages

on:
  push:
    branches: [ "*" ]
env:
  ASPNETCORE_ENVIRONMENT: Production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Remove launchSettings.json (to not override ASPNETCORE_ENVIRONMENT)
        run: rm /Properties/launchSettings.json

      - name: Tailwind - download and run cli
        run: |
          wget https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -O /usr/local/bin/tailwindcss
          chmod +x /usr/local/bin/tailwindcss
         
          tailwindcss --input ./wwwroot/app.css  --output ./wwwroot/app.min.css  --minify
    
      - name: Change <base href="" /> in App.razor to match gh repo name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | awk -F '/' '{print $NF}')
          sed -i 's/<base href="\/" \/>/<base href="\/'$REPO_NAME'\/" \/>/g' Components/App.razor

      - name: Run webapp and generate static files
        run: |
          dotnet run --configuration Release

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
  
  
  